version: 1.0
provider:
  name: openfaas
  gateway: https://gateway.on9.webredirect.org
functions:
  silly-tavern-api:
    lang: golang-middleware
    handler: ./stack
    image: core.harbor.on9.webredirect.org/silly-tavern/silly-tavern-api:latest
    secrets:
      - harbor-user
